//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        public int LabSerial { get; set; }
        public Nullable<int> BranchSerial { get; set; }
        public Nullable<int> FacultySerial { get; set; }
        public string LabNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Floor { get; set; }
        public string Location { get; set; }
    }
}
