//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int ModuleSerial { get; set; }
        public Nullable<int> CourseSerial { get; set; }
        public string ModuleId { get; set; }
        public string Name { get; set; }
        public string Credit { get; set; }
    }
}
