//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentSerial { get; set; }
        public Nullable<int> BatchSerial { get; set; }
        public string RegNo { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Year { get; set; }
        public string RegCampus { get; set; }
    }
}
