//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TTMS_DBEntities : DbContext
    {
        public TTMS_DBEntities()
            : base("name=TTMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Lab> Labs { get; set; }
        public virtual DbSet<LectureHall> LectureHalls { get; set; }
        public virtual DbSet<Lecturer> Lecturers { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<Reschedule> Reschedules { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual ObjectResult<rptGetLecturerDetailsByLecturerSerial_Result> rptGetLecturerDetailsByLecturerSerial(Nullable<int> lecturerSerial)
        {
            var lecturerSerialParameter = lecturerSerial.HasValue ?
                new ObjectParameter("LecturerSerial", lecturerSerial) :
                new ObjectParameter("LecturerSerial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptGetLecturerDetailsByLecturerSerial_Result>("rptGetLecturerDetailsByLecturerSerial", lecturerSerialParameter);
        }
    }
}
